import Nav from '@/components/nav'
import './globals.css'
import type { Metadata } from 'next'
import { Fira_Code } from 'next/font/google'
import Footer from '@/components/Footer'
import SideBar from '@/components/sideBar'

const inter = Fira_Code({ preload: true, subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='flex flex-col min-h-screen  w-full py-5 px-5 bg-black text-sm overflow-hidden'>
					<div className='flex flex-col border-[1px] border-[#607B96]/50 rounded-md h-full grow bg-background'>
						<Nav />
						<div className='flex grow'>
							<SideBar />
							<div className='flex flex-col grow'>{children}</div>
						</div>
						<Footer />
					</div>
				</div>
			</body>
		</html>
	)
}
