import Nav from '@/components/nav'
import './globals.css'
import type { Metadata } from 'next'
import { Fira_Code } from 'next/font/google'
import Footer from '@/components/Footer'
import SideBar from '@/components/sideBar'
import FileNav from '@/components/FileNav'
import Divider from '@/components/Divider'

const inter = Fira_Code({ preload: true, subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen w-full  flex-col overflow-hidden bg-black px-5 py-5 text-sm">
          <div className="flex h-full grow flex-col rounded-md border-[1px] border-[#607B96]/50 bg-background">
            <Nav />
            <Divider dir="horizontal" />
            <div className="flex w-full grow">
              <SideBar />
              <Divider dir="vertical" />
              <div className="flex grow flex-col">
                <FileNav />
                <div className="flex grow flex-col items-center justify-center overflow-auto">
                  {children}
                </div>
              </div>
            </div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}
